@startuml
left to right direction
skinparam packageStyle rectangle

actor "Адміністратор" as Admin

rectangle "Система книжкового каталогу" {

    Admin -- (Зареєструвати користувача)
    Admin -- (Додати книгу)
    Admin -- (Видалити книгу)
    Admin -- (Пошук книги)
    Admin -- (Забронювати книгу)
    Admin -- (Зняти бронювання)
    Admin -- (Видалити користувача)

    (Забронювати книгу) .> (Перевірка існування книги) : <<include>>
    (Забронювати книгу) .> (Перевірка існування користувача) : <<include>>
    (Забронювати книгу) .> (Перевірка доступності книги) : <<include>>

    (Видалити книгу) .> (Перевірка бронювання книги) : <<include>>
    (Видалити користувача) .> (Перевірка активного бронювання) : <<include>>
}

@enduml